version: '3.8'

services:
  # Servicio para Apache PHP
  app:
    build:
      dockerfile: docker/httpd/Dockerfile
    #restart: unless-stopped
    ports:
      - "${HTTPD_PORT}:80"
    working_dir: /var/www/html
    networks:
      - laravel_network

  # Servicio para MySQL
  db:
    image: mysql:5.7
    #restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  # Servicio para phpMyAdmin (opcional)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: laravel_phpmyadmin
  #   restart: unless-stopped
  #   ports:
  #     - "${PHPMYADMIN_PORT}:80"
  #   environment:
  #     PMA_HOST: db
  #   depends_on:
  #     - db
  #   networks:
  #     - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
